[build-system]
# Minimum requirements for the build system to execute.
# The build also requires torch, but it is a complex dependency that is
# dealt with in setup.py
requires = [
    "setuptools",
    "wheel",
]
