import torch
from ..modules._base import Module
from ...core.utils import expand, unsqueeze, ensure_shape, info
from ...core.constants import pi
from ...core.kernels import smooth
import math


class RandomFieldSample(Module):
    """Sample a smooth random field.

    The field is generated by sampling white Gaussian noise and
    convolving it with a Gaussian kernel.

    """

    def __init__(self, shape=None, mean=0, amplitude=1, fwhm=1, channel=1,
                 basis=1, device='cpu', dtype=torch.get_default_dtype()):
        """

        Parameters
        ----------
        shape : sequence[int], optional
            Lattice shape
        mean : callable or tensor, default=0
            Mean value. Should broadcast to (channel, *shape)
        amplitude : callable or tensor, default=1
            Amplitude of the squared-exponential kernel.
            Should broadcast to (channel, *shape)
        fwhm : callable or tensor, default=1
            Full-width at Half Maximum of the squared-exponential kernel.
            Should broadcast to (channel, ndim)
        channel : int, default=1
            Number of channels
        basis : {0, 1}, default=1
            See `nitorch.core.kernels.smooth`
        device : torch.device: default='cpu'
            Output tensor device.
        dtype : torch.dtype, default=torch.get_default_dtype()
            Output tensor datatype.

        """
        super().__init__()
        self.shape = shape
        self.mean = mean
        self.amplitude = amplitude
        self.fwhm = fwhm
        self.channel = channel
        self.basis = basis
        self.device = device
        self.dtype = dtype if dtype.is_floating_point \
            else torch.get_default_dtype()

    def forward(self, batch=1, **overload):
        """

        Parameters
        ----------
        batch : int, default=1
            Batch size
        overload : dict

        Returns
        -------
        field : (batch, channel, *shape) tensor
            Generated random field

        """

        # get arguments
        shape = overload.get('shape', self.shape)
        mean = overload.get('mean', self.mean)
        amplitude = overload.get('amplitude', self.amplitude)
        fwhm = overload.get('fwhm', self.fwhm)
        channel = overload.get('channel', self.channel)
        basis = overload.get('basis', self.basis)
        dtype = overload.get('dtype', self.dtype)
        device = overload.get('device', self.device)

        # sample if parameters are callable
        mean = mean() if callable(mean) else mean
        amplitude = amplitude() if callable(amplitude) else amplitude
        fwhm = fwhm() if callable(fwhm) else fwhm

        # device/dtype
        mean = torch.as_tensor(mean, dtype=dtype, device=device)
        amplitude = torch.as_tensor(amplitude, dtype=dtype, device=device)
        fwhm = torch.as_tensor(fwhm, dtype=dtype, device=device)

        # reshape
        nb_dim = len(shape)
        full_shape = [batch, channel, *shape]
        mean = mean.expand(full_shape)
        amplitude = amplitude.expand(full_shape)
        fwhm = fwhm.expand([basis, channel, nb_dim])

        conv = torch.nn.functional.conv1d if nb_dim == 1 else \
               torch.nn.functional.conv2d if nb_dim == 2 else \
               torch.nn.functional.conv3d if nb_dim == 3 else None

        # convert SE parameters to noise/kernel parameters
        sigma_se = fwhm / math.sqrt(8*math.log(2))
        sigma_se = unsqueeze(sigma_se.prod(dim=-1), dim=-1, ndim=nb_dim)
        amplitude = amplitude * (2*pi)**(nb_dim/4) * sigma_se.sqrt()
        fwhm = fwhm * math.sqrt(2)

        # smooth
        samples_b = []
        for b in range(batch):
            samples_c = []
            for c in range(channel):
                kernel = smooth('gauss', fwhm[b, c], basis=basis,
                                device=device, dtype=dtype)

                # compute input shape
                pad_shape = [shape[d] + kernel[d].shape[d+2] - 1
                             for d in range(nb_dim)]
                mean1 = ensure_shape(mean[b, c], pad_shape,
                                     mode='reflect2', side='both')
                amplitude1 = ensure_shape(amplitude[b, c], pad_shape,
                                          mode='reflect2', side='both')

                # generate sample
                sample = torch.distributions.Normal(mean1, amplitude1).sample()
                sample = sample[None, None, ...]

                # convolve
                for ker in kernel:
                    sample = conv(sample, ker)

                samples_c.append(sample)

            samples_b.append(torch.cat(samples_c, dim=1))

        sample = torch.cat(samples_b, dim=0)

        return sample
